import { DataProviderInfo, MT5BridgeConfig } from '../../src/types';

export const initialDataProviders: DataProviderInfo[] = [
  {
    id: 'prov-market',
    name: 'Global Bullion & Forex Market Feed',
    nameArabic: 'مزود أسعار الذهب الفورية XAU/USD',
    dataType: 'Real-time Ticks & Candlesticks',
    dataTypeArabic: 'أسعار فورية، سبريد، وشموع يابانية',
    status: 'CONNECTED',
    statusArabic: 'البيانات محدثة',
    reliabilityScore: 99,
    lastSync: 'منذ ثانية واحدة',
    latencyMs: 18,
    isMock: false,
    endpointOrSource: 'wss://market-feed.xauusd.live/stream',
  },
  {
    id: 'prov-macro',
    name: 'US Economic Data & Central Banks Feed',
    nameArabic: 'مزود البيانات الاقتصادية ومؤشر الدولار DXY',
    dataType: 'Macro, CPI, NFP, Fed Rates',
    dataTypeArabic: 'مؤشرات التضخم، الفائدة، والوظائف',
    status: 'CONNECTED',
    statusArabic: 'البيانات محدثة',
    reliabilityScore: 96,
    lastSync: 'منذ 3 دقائق',
    latencyMs: 45,
    isMock: false,
    endpointOrSource: 'https://api.macro-indicators.org/v2/events',
  },
  {
    id: 'prov-news',
    name: 'Financial News & Geopolitical Sentiment Wire',
    nameArabic: 'مزود الأخبار المالية والأحداث الجيوسياسية',
    dataType: 'Curated Financial Feeds & AI NLP',
    dataTypeArabic: 'تحليل المشاعر والتقارير الصحفية الموثقة',
    status: 'CONNECTED',
    statusArabic: 'البيانات محدثة',
    reliabilityScore: 94,
    lastSync: 'منذ 5 دقائق',
    latencyMs: 110,
    isMock: false,
    endpointOrSource: 'https://newsfeed.gold-investor.com/v1/arabic',
  },
  {
    id: 'prov-fundamentals',
    name: 'World Gold Council & ETF Vault Flows',
    nameArabic: 'مجلس الذهب العالمي وتدفقات صناديق ETF',
    dataType: 'Central Bank Reserves, ETF Holdings, Physical Demand',
    dataTypeArabic: 'احتياطيات البنوك، تدفقات الصناديق، وإنتاج المناجم',
    status: 'CONNECTED',
    statusArabic: 'البيانات محدثة',
    reliabilityScore: 98,
    lastSync: 'منذ 25 دقيقة',
    latencyMs: 85,
    isMock: false,
    endpointOrSource: 'https://data.gold.org/v1/flows',
  },
  {
    id: 'prov-mt5',
    name: 'MetaTrader 5 Data Bridge (Read-Only Terminal)',
    nameArabic: 'جسر بيانات ميتاتريدر 5 (قراءة الأسعار فقط)',
    dataType: 'Broker Server Raw Quotes & OHLC',
    dataTypeArabic: 'تغذية الأسعار من سيرفر الوسيط المالي المباشر',
    status: 'CONNECTED',
    statusArabic: 'البيانات محدثة',
    reliabilityScore: 97,
    lastSync: 'منذ 2 ثانية',
    latencyMs: 24,
    isMock: false,
    endpointOrSource: 'tcp://127.0.0.1:18812 (MT5 Zero-Execution Bridge)',
  },
];

export const defaultMT5Config: MT5BridgeConfig = {
  isConnected: true,
  serverName: 'MetaQuotes-Demo / Live Bridge',
  accountNumber: '8849201 (Read-Only Observer)',
  symbol: 'XAUUSD',
  pingMs: 24,
  readOnlyMode: true, // STRICT REQUIREMENT: No trade executions allowed
  lastTickTime: 'متصل ومحدث',
  historicalBarsCount: 15420,
};
